// Banco de dados dos blocos de Breed do Pixelmon traduzidos para o Português
const BREED_DATA = {
  bug: {
    name: "Inseto",
    color: "#A8B820",
    icon: "🐛",
    blocks: [
      { id: "dandelion", pt: "Dente-de-leão", points: 2 },
      { id: "poppy", pt: "Papoula", points: 2 },
      { id: "blue_orchid", pt: "Orquídea Azul", points: 2 },
      { id: "allium", pt: "Alho-silvestre", points: 2 },
      { id: "azure_bluet", pt: "Suspiro", points: 2 },
      { id: "red_tulip", pt: "Tulipa Vermelha", points: 2 },
      { id: "orange_tulip", pt: "Tulipa Laranja", points: 2 },
      { id: "white_tulip", pt: "Tulipa Branca", points: 2 },
      { id: "pink_tulip", pt: "Tulipa Rosa", points: 2 },
      { id: "oxeye_daisy", pt: "Margarida", points: 2 },
      { id: "cornflower", pt: "Centáurea", points: 2 },
      { id: "lily_of_the_valley", pt: "Lírio-do-vale", points: 2 },
      { id: "wither_rose", pt: "Rosa do Wither", points: 2 },
      { id: "sunflower", pt: "Girassol", points: 2 },
      { id: "lilac", pt: "Lilás", points: 2 },
      { id: "peony", pt: "Peônia", points: 2 },
      { id: "rose_bush", pt: "Arbusto de Rosa", points: 2 },
      { id: "jungle_leaves", pt: "Folhas de Selva", points: 1 },
      { id: "oak_leaves", pt: "Folhas de Carvalho", points: 1 },
      { id: "spruce_leaves", pt: "Folhas de Pinheiro", points: 1 },
      { id: "dark_oak_leaves", pt: "Folhas de Carvalho Escuro", points: 1 },
      { id: "acacia_leaves", pt: "Folhas de Acácia", points: 1 },
      { id: "birch_leaves", pt: "Folhas de Bétula", points: 1 },
      { id: "pixelmon:berry_leaves_cheri", pt: "Folhas de Fruta Cheri", points: 1 },
      { id: "pixelmon:berry_leaves_chesto", pt: "Folhas de Fruta Chesto", points: 1 },
      { id: "pixelmon:berry_leaves_pecha", pt: "Folhas de Fruta Pecha", points: 1 },
      { id: "pixelmon:berry_leaves_rawst", pt: "Folhas de Fruta Rawst", points: 1 },
      { id: "pixelmon:berry_leaves_aspear", pt: "Folhas de Fruta Aspear", points: 1 },
      { id: "pixelmon:berry_leaves_leppa", pt: "Folhas de Fruta Leppa", points: 1 },
      { id: "pixelmon:berry_leaves_oran", pt: "Folhas de Fruta Oran", points: 1 },
      { id: "pixelmon:berry_leaves_persim", pt: "Folhas de Fruta Persim", points: 1 },
      { id: "pixelmon:berry_leaves_lum", pt: "Folhas de Fruta Lum", points: 1 },
      { id: "pixelmon:berry_leaves_sitrus", pt: "Folhas de Fruta Sitrus", points: 1 },
      { id: "pixelmon:berry_leaves_figy", pt: "Folhas de Fruta Figy", points: 1 },
      { id: "pixelmon:berry_leaves_wiki", pt: "Folhas de Fruta Wiki", points: 1 },
      { id: "pixelmon:berry_leaves_mago", pt: "Folhas de Fruta Mago", points: 1 },
      { id: "pixelmon:berry_leaves_iapapa", pt: "Folhas de Fruta Iapapa", points: 1 },
      { id: "pixelmon:berry_leaves_razz", pt: "Folhas de Fruta Razz", points: 1 },
      { id: "pixelmon:berry_leaves_bluk", pt: "Folhas de Fruta Bluk", points: 1 },
      { id: "pixelmon:berry_leaves_nanab", pt: "Folhas de Fruta Nanab", points: 1 },
      { id: "pixelmon:berry_leaves_wepear", pt: "Folhas de Fruta Wepear", points: 1 },
      { id: "pixelmon:berry_leaves_pinap", pt: "Folhas de Fruta Pinap", points: 1 },
      { id: "pixelmon:berry_leaves_pomeg", pt: "Folhas de Fruta Pomeg", points: 1 },
      { id: "pixelmon:berry_leaves_kelpsy", pt: "Folhas de Fruta Kelpsy", points: 1 },
      { id: "pixelmon:berry_leaves_qualot", pt: "Folhas de Fruta Qualot", points: 1 },
      { id: "pixelmon:berry_leaves_hondew", pt: "Folhas de Fruta Hondew", points: 1 },
      { id: "pixelmon:berry_leaves_grepa", pt: "Folhas de Fruta Grepa", points: 1 },
      { id: "pixelmon:berry_leaves_tamato", pt: "Folhas de Fruta Tamato", points: 1 },
      { id: "pixelmon:berry_leaves_cornn", pt: "Folhas de Fruta Cornn", points: 1 },
      { id: "pixelmon:berry_leaves_magost", pt: "Folhas de Fruta Magost", points: 1 },
      { id: "pixelmon:berry_leaves_rabuta", pt: "Folhas de Fruta Rabuta", points: 1 },
      { id: "pixelmon:berry_leaves_nomel", pt: "Folhas de Fruta Nomel", points: 1 },
      { id: "pixelmon:berry_leaves_spelon", pt: "Folhas de Fruta Spelon", points: 1 },
      { id: "pixelmon:berry_leaves_pamtre", pt: "Folhas de Fruta Pamtre", points: 1 },
      { id: "pixelmon:berry_leaves_watmel", pt: "Folhas de Fruta Watmel", points: 1 },
      { id: "pixelmon:berry_leaves_durin", pt: "Folhas de Fruta Durin", points: 1 },
      { id: "pixelmon:berry_leaves_belue", pt: "Folhas de Fruta Belue", points: 1 },
      { id: "pixelmon:berry_leaves_occa", pt: "Folhas de Fruta Occa", points: 1 },
      { id: "pixelmon:berry_leaves_passho", pt: "Folhas de Fruta Passho", points: 1 },
      { id: "pixelmon:berry_leaves_wacan", pt: "Folhas de Fruta Wacan", points: 1 },
      { id: "pixelmon:berry_leaves_rindo", pt: "Folhas de Fruta Rindo", points: 1 },
      { id: "pixelmon:berry_leaves_yache", pt: "Folhas de Fruta Yache", points: 1 },
      { id: "pixelmon:berry_leaves_chople", pt: "Folhas de Fruta Chople", points: 1 },
      { id: "pixelmon:berry_leaves_kebia", pt: "Folhas de Fruta Kebia", points: 1 },
      { id: "pixelmon:berry_leaves_shuca", pt: "Folhas de Fruta Shuca", points: 1 },
      { id: "pixelmon:berry_leaves_coba", pt: "Folhas de Fruta Coba", points: 1 },
      { id: "pixelmon:berry_leaves_payapa", pt: "Folhas de Fruta Payapa", points: 1 },
      { id: "pixelmon:berry_leaves_tanga", pt: "Folhas de Fruta Tanga", points: 1 },
      { id: "pixelmon:berry_leaves_charti", pt: "Folhas de Fruta Charti", points: 1 },
      { id: "pixelmon:berry_leaves_kasib", pt: "Folhas de Fruta Kasib", points: 1 },
      { id: "pixelmon:berry_leaves_haban", pt: "Folhas de Fruta Haban", points: 1 },
      { id: "pixelmon:berry_leaves_colbur", pt: "Folhas de Fruta Colbur", points: 1 },
      { id: "pixelmon:berry_leaves_babiri", pt: "Folhas de Fruta Babiri", points: 1 },
      { id: "pixelmon:berry_leaves_chilan", pt: "Folhas de Fruta Chilan", points: 1 },
      { id: "pixelmon:berry_leaves_roseli", pt: "Folhas de Fruta Roseli", points: 1 },
      { id: "pixelmon:berry_leaves_liechi", pt: "Folhas de Fruta Liechi", points: 1 },
      { id: "pixelmon:berry_leaves_ganlon", pt: "Folhas de Fruta Ganlon", points: 1 },
      { id: "pixelmon:berry_leaves_salac", pt: "Folhas de Fruta Salac", points: 1 },
      { id: "pixelmon:berry_leaves_petaya", pt: "Folhas de Fruta Petaya", points: 1 },
      { id: "pixelmon:berry_leaves_apicot", pt: "Folhas de Fruta Apicot", points: 1 },
      { id: "pixelmon:berry_leaves_lansat", pt: "Folhas de Fruta Lansat", points: 1 },
      { id: "pixelmon:berry_leaves_starf", pt: "Folhas de Fruta Starf", points: 1 },
      { id: "pixelmon:berry_leaves_pumkin", pt: "Folhas de Fruta Pumkin", points: 1 },
      { id: "pixelmon:berry_leaves_drash", pt: "Folhas de Fruta Drash", points: 1 },
      { id: "pixelmon:berry_leaves_eggant", pt: "Folhas de Fruta Eggant", points: 1 },
      { id: "pixelmon:berry_leaves_strib", pt: "Folhas de Fruta Strib", points: 1 },
      { id: "pixelmon:berry_leaves_nutpea", pt: "Folhas de Fruta Nutpea", points: 1 },
      { id: "pixelmon:berry_leaves_ginema", pt: "Folhas de Fruta Ginema", points: 1 },
      { id: "pixelmon:berry_leaves_kuo", pt: "Folhas de Fruta Kuo", points: 1 },
      { id: "pixelmon:berry_leaves_yago", pt: "Folhas de Fruta Yago", points: 1 },
      { id: "pixelmon:berry_leaves_touga", pt: "Folhas de Fruta Touga", points: 1 },
      { id: "pixelmon:berry_leaves_niniku", pt: "Folhas de Fruta Niniku", points: 1 },
      { id: "pixelmon:berry_leaves_topo", pt: "Folhas de Fruta Topo", points: 1 },
      { id: "pixelmon:berry_leaves_enigma", pt: "Folhas de Fruta Enigma", points: 1 },
      { id: "pixelmon:berry_leaves_micle", pt: "Folhas de Fruta Micle", points: 1 },
      { id: "pixelmon:berry_leaves_jaboca", pt: "Folhas de Fruta Jaboca", points: 1 },
      { id: "pixelmon:berry_leaves_rowap", pt: "Folhas de Fruta Rowap", points: 1 },
      { id: "pixelmon:berry_leaves_kee", pt: "Folhas de Fruta Kee", points: 1 },
      { id: "pixelmon:berry_leaves_maranga", pt: "Folhas de Fruta Maranga", points: 1 },
      { id: "pixelmon:berry_leaves_aguav", pt: "Folhas de Fruta Aguav", points: 1 },
      { id: "pixelmon:berry_leaves_custap", pt: "Folhas de Fruta Custap", points: 1 },
      { id: "pixelmon:apricorn_leaves_black", pt: "Folhas de Apricorn Preto", points: 1 },
      { id: "pixelmon:apricorn_leaves_blue", pt: "Folhas de Apricorn Azul", points: 1 },
      { id: "pixelmon:apricorn_leaves_green", pt: "Folhas de Apricorn Verde", points: 1 },
      { id: "pixelmon:apricorn_leaves_pink", pt: "Folhas de Apricorn Rosa", points: 1 },
      { id: "pixelmon:apricorn_leaves_red", pt: "Folhas de Apricorn Vermelho", points: 1 },
      { id: "pixelmon:apricorn_leaves_white", pt: "Folhas de Apricorn Branco", points: 1 },
      { id: "pixelmon:apricorn_leaves_yellow", pt: "Folhas de Apricorn Amarelo", points: 1 },
      { id: "pixelmon:ultra_jungle_leaves", pt: "Folhas de Selva Ultra", points: 1 },
      { id: "pixelmon:ultra_gingko_leaves", pt: "Folhas de Ginkgo Ultra", points: 1 },
      { id: "pixelmon:ultra_elm_leaves", pt: "Folhas de Olmo Ultra", points: 1 },
      { id: "dark_oak_log", pt: "Tronco de Carvalho Escuro", points: 1 },
      { id: "dark_oak_wood", pt: "Madeira de Carvalho Escuro", points: 1 },
      { id: "stripped_dark_oak_log", pt: "Tronco de Carvalho Escuro Descascado", points: 1 },
      { id: "stripped_dark_oak_wood", pt: "Madeira de Carvalho Escuro Descascada", points: 1 },
      { id: "oak_log", pt: "Tronco de Carvalho", points: 1 },
      { id: "oak_wood", pt: "Madeira de Carvalho", points: 1 },
      { id: "stripped_oak_log", pt: "Tronco de Carvalho Descascado", points: 1 },
      { id: "stripped_oak_wood", pt: "Madeira de Carvalho Descascada", points: 1 },
      { id: "acacia_log", pt: "Tronco de Acácia", points: 1 },
      { id: "acacia_wood", pt: "Madeira de Acácia", points: 1 },
      { id: "stripped_acacia_log", pt: "Tronco de Acácia Descascado", points: 1 },
      { id: "stripped_acacia_wood", pt: "Madeira de Acácia Descascada", points: 1 },
      { id: "birch_log", pt: "Tronco de Bétula", points: 1 },
      { id: "birch_wood", pt: "Madeira de Bétula", points: 1 },
      { id: "stripped_birch_log", pt: "Tronco de Bétula Descascado", points: 1 },
      { id: "stripped_birch_wood", pt: "Madeira de Bétula Descascada", points: 1 },
      { id: "jungle_log", pt: "Tronco de Selva", points: 1 },
      { id: "jungle_wood", pt: "Madeira de Selva", points: 1 },
      { id: "stripped_jungle_log", pt: "Tronco de Selva Descascado", points: 1 },
      { id: "stripped_jungle_wood", pt: "Madeira de Selva Descascada", points: 1 },
      { id: "spruce_log", pt: "Tronco de Pinheiro", points: 1 },
      { id: "spruce_wood", pt: "Madeira de Pinheiro", points: 1 },
      { id: "stripped_spruce_log", pt: "Tronco de Pinheiro Descascado", points: 1 },
      { id: "stripped_spruce_wood", pt: "Madeira de Pinheiro Descascada", points: 1 },
      { id: "crimson_stem", pt: "Caule Carmesim", points: 1 },
      { id: "stripped_crimson_stem", pt: "Caule Carmesim Descascado", points: 1 },
      { id: "crimson_hyphae", pt: "Hifas Carmesim", points: 1 },
      { id: "stripped_crimson_hyphae", pt: "Hifas Carmesim Descascadas", points: 1 },
      { id: "warped_stem", pt: "Caule Distorcido", points: 1 },
      { id: "stripped_warped_stem", pt: "Caule Distorcido Descascado", points: 1 },
      { id: "warped_hyphae", pt: "Hifas Distorcidas", points: 1 },
      { id: "stripped_warped_hyphae", pt: "Hifas Distorcidas Descascadas", points: 1 },
      { id: "pixelmon:berry_log", pt: "Tronco de Fruta (Pixelmon)", points: 1 },
      { id: "pixelmon:apricorn_log", pt: "Tronco de Apricorn (Pixelmon)", points: 1 },
      { id: "pixelmon:ultra_jungle_log", pt: "Tronco de Ultra Selva", points: 1 },
      { id: "pixelmon:ultra_gingko_log", pt: "Tronco de Ultra Ginkgo", points: 1 },
      { id: "pixelmon:ultra_elm_log", pt: "Tronco de Ultra Olmo", points: 1 },
      { id: "flower_pot", pt: "Vaso de Flor", points: 3 },
      { id: "grass_block", pt: "Bloco de Grama", points: 1 },
      { id: "brown_mushroom_block", pt: "Bloco de Cogumelo Marrom", points: 2 },
      { id: "red_mushroom_block", pt: "Bloco de Cogumelo Vermelho", points: 3 }
    ]
  },
  dark: {
    name: "Sombrio",
    color: "#705848",
    icon: "🌙",
    blocks: [
      { id: "coal_block", pt: "Bloco de Carvão", points: 3 },
      { id: "cobweb", pt: "Teia de Aranha", points: 2 },
      { id: "creeper_head", pt: "Cabeça de Creeper", points: 4 },
      { id: "zombie_head", pt: "Cabeça de Zumbi", points: 4 },
      { id: "skeleton_skull", pt: "Crânio de Esqueleto", points: 4 },
      { id: "wither_skeleton_skull", pt: "Crânio de Esqueleto Wither", points: 4 },
      { id: "nether_bricks", pt: "Tijolos do Nether", points: 2 },
      { id: "obsidian", pt: "Obsidiana", points: 2 },
      { id: "sand", pt: "Areia", points: 1 },
      { id: "soul_sand", pt: "Areia de Almas", points: 2 }
    ]
  },
  dragon: {
    name: "Dragão",
    color: "#7038F8",
    icon: "🐉",
    blocks: [
      { id: "diamond_block", pt: "Bloco de Diamante", points: 3 },
      { id: "emerald_block", pt: "Bloco de Esmeralda", points: 3 },
      { id: "gold_block", pt: "Bloco de Ouro", points: 2 },
      { id: "dragon_egg", pt: "Ovo de Dragão", points: 4 },
      { id: "enchanting_table", pt: "Mesa de Encantamentos", points: 3 },
      { id: "end_stone", pt: "Pedra do Fim", points: 3 },
      { id: "glowstone", pt: "Pedra Luminosa", points: 2 },
      { id: "stone", pt: "Pedra", points: 1 }
    ]
  },
  electric: {
    name: "Elétrico",
    color: "#F8D030",
    icon: "⚡",
    blocks: [
      { id: "activator_rail", pt: "Trilho Ativador", points: 2 },
      { id: "redstone_block", pt: "Bloco de Redstone", points: 2 },
      { id: "pixelmon:white_pc", pt: "PC Branco", points: 3 },
      { id: "pixelmon:orange_pc", pt: "PC Laranja", points: 3 },
      { id: "pixelmon:magenta_pc", pt: "PC Magenta", points: 3 },
      { id: "pixelmon:light_blue_pc", pt: "PC Azul Claro", points: 3 },
      { id: "pixelmon:yellow_pc", pt: "PC Amarelo", points: 3 },
      { id: "pixelmon:lime_pc", pt: "PC Lima", points: 3 },
      { id: "pixelmon:pink_pc", pt: "PC Rosa", points: 3 },
      { id: "pixelmon:gray_pc", pt: "PC Cinza", points: 3 },
      { id: "pixelmon:light_gray_pc", pt: "PC Cinza Claro", points: 3 },
      { id: "pixelmon:cyan_pc", pt: "PC Ciano", points: 3 },
      { id: "pixelmon:purple_pc", pt: "PC Roxo", points: 3 },
      { id: "pixelmon:blue_pc", pt: "PC Azul", points: 3 },
      { id: "pixelmon:brown_pc", pt: "PC Marrom", points: 3 },
      { id: "pixelmon:green_pc", pt: "PC Verde", points: 3 },
      { id: "pixelmon:red_pc", pt: "PC Vermelho", points: 3 },
      { id: "pixelmon:black_pc", pt: "PC Preto", points: 3 },
      { id: "rail", pt: "Trilho", points: 1 },
      { id: "redstone_lamp[lit=false]", pt: "Lâmpada de Redstone (Apagada)", points: 1 },
      { id: "redstone_lamp[lit=true]", pt: "Lâmpada de Redstone (Acesa)", points: 3 },
      { id: "redstone_ore", pt: "Minério de Redstone", points: 2 }
    ]
  },
  fairy: {
    name: "Fada",
    color: "#EE99AC",
    icon: "🌸",
    blocks: [
      { id: "cake", pt: "Bolo", points: 3 },
      { id: "white_carpet", pt: "Tapete Branco", points: 1 },
      { id: "orange_carpet", pt: "Tapete Laranja", points: 1 },
      { id: "magenta_carpet", pt: "Tapete Magenta", points: 1 },
      { id: "light_blue_carpet", pt: "Tapete Azul Claro", points: 1 },
      { id: "yellow_carpet", pt: "Tapete Amarelo", points: 1 },
      { id: "lime_carpet", pt: "Tapete Lima", points: 1 },
      { id: "pink_carpet", pt: "Tapete Rosa", points: 1 },
      { id: "gray_carpet", pt: "Tapete Cinza", points: 1 },
      { id: "light_gray_carpet", pt: "Tapete Cinza Claro", points: 1 },
      { id: "cyan_carpet", pt: "Tapete Ciano", points: 1 },
      { id: "purple_carpet", pt: "Tapete Roxo", points: 1 },
      { id: "blue_carpet", pt: "Tapete Azul", points: 1 },
      { id: "brown_carpet", pt: "Tapete Marrom", points: 1 },
      { id: "green_carpet", pt: "Tapete Verde", points: 1 },
      { id: "red_carpet", pt: "Tapete Vermelho", points: 1 },
      { id: "black_carpet", pt: "Tapete Preto", points: 1 },
      { id: "glowstone", pt: "Pedra Luminosa", points: 2 },
      { id: "white_wool", pt: "Lã Branca", points: 2 },
      { id: "orange_wool", pt: "Lã Laranja", points: 2 },
      { id: "magenta_wool", pt: "Lã Magenta", points: 2 },
      { id: "light_blue_wool", pt: "Lã Azul Claro", points: 2 },
      { id: "yellow_wool", pt: "Lã Amarela", points: 2 },
      { id: "lime_wool", pt: "Lã Lima", points: 2 },
      { id: "pink_wool", pt: "Lã Rosa", points: 2 },
      { id: "gray_wool", pt: "Lã Cinza", points: 2 },
      { id: "light_gray_wool", pt: "Lã Cinza Claro", points: 2 },
      { id: "cyan_wool", pt: "Lã Ciana", points: 2 },
      { id: "purple_wool", pt: "Lã Roxa", points: 2 },
      { id: "blue_wool", pt: "Lã Azul", points: 2 },
      { id: "brown_wool", pt: "Lã Marrom", points: 2 },
      { id: "green_wool", pt: "Lã Verde", points: 2 },
      { id: "red_wool", pt: "Lã Vermelha", points: 2 },
      { id: "black_wool", pt: "Lã Preta", points: 2 }
    ]
  },
  fighting: {
    name: "Lutador",
    color: "#C03028",
    icon: "🥊",
    blocks: [
      { id: "anvil", pt: "Bigorna", points: 2 },
      { id: "chipped_anvil", pt: "Bigorna Danificada", points: 2 },
      { id: "damaged_anvil", pt: "Bigorna Muito Danificada", points: 2 },
      { id: "bricks", pt: "Tijolos", points: 2 },
      { id: "brick_stairs", pt: "Escada de Tijolos", points: 2 },
      { id: "chiseled_stone_bricks", pt: "Tijolos de Pedra Talhados", points: 3 },
      { id: "cracked_stone_bricks", pt: "Tijolos de Pedra Rachados", points: 3 },
      { id: "gravel", pt: "Cascalho", points: 1 },
      { id: "mossy_stone_bricks", pt: "Tijolos de Pedra Musgosos", points: 3 },
      { id: "stone_bricks", pt: "Tijolos de Pedra", points: 3 },
      { id: "pixelmon:temple_brick", pt: "Tijolo de Templo", points: 2 },
      { id: "pixelmon:temple_brick_stairs", pt: "Escada de Tijolo de Templo", points: 2 }
    ]
  },
  fire: {
    name: "Fogo",
    color: "#F08030",
    icon: "🔥",
    blocks: [
      { id: "dark_oak_log", pt: "Tronco de Carvalho Escuro", points: 1 },
      { id: "dark_oak_wood", pt: "Madeira de Carvalho Escuro", points: 1 },
      { id: "stripped_dark_oak_log", pt: "Tronco de Carvalho Escuro Descascado", points: 1 },
      { id: "stripped_dark_oak_wood", pt: "Madeira de Carvalho Escuro Descascada", points: 1 },
      { id: "oak_log", pt: "Tronco de Carvalho", points: 1 },
      { id: "oak_wood", pt: "Madeira de Carvalho", points: 1 },
      { id: "stripped_oak_log", pt: "Tronco de Carvalho Descascado", points: 1 },
      { id: "stripped_oak_wood", pt: "Madeira de Carvalho Descascada", points: 1 },
      { id: "acacia_log", pt: "Tronco de Acácia", points: 1 },
      { id: "acacia_wood", pt: "Madeira de Acácia", points: 1 },
      { id: "stripped_acacia_log", pt: "Tronco de Acácia Descascado", points: 1 },
      { id: "stripped_acacia_wood", pt: "Madeira de Acácia Descascada", points: 1 },
      { id: "birch_log", pt: "Tronco de Bétula", points: 1 },
      { id: "birch_wood", pt: "Madeira de Bétula", points: 1 },
      { id: "stripped_birch_log", pt: "Tronco de Bétula Descascado", points: 1 },
      { id: "stripped_birch_wood", pt: "Madeira de Bétula Descascada", points: 1 },
      { id: "jungle_log", pt: "Tronco de Selva", points: 1 },
      { id: "jungle_wood", pt: "Madeira de Selva", points: 1 },
      { id: "stripped_jungle_log", pt: "Tronco de Selva Descascado", points: 1 },
      { id: "stripped_jungle_wood", pt: "Madeira de Selva Descascada", points: 1 },
      { id: "spruce_log", pt: "Tronco de Pinheiro", points: 1 },
      { id: "spruce_wood", pt: "Madeira de Pinheiro", points: 1 },
      { id: "stripped_spruce_log", pt: "Tronco de Pinheiro Descascado", points: 1 },
      { id: "stripped_spruce_wood", pt: "Madeira de Pinheiro Descascada", points: 1 },
      { id: "crimson_stem", pt: "Caule Carmesim", points: 1 },
      { id: "stripped_crimson_stem", pt: "Caule Carmesim Descascado", points: 1 },
      { id: "crimson_hyphae", pt: "Hifas Carmesim", points: 1 },
      { id: "stripped_crimson_hyphae", pt: "Hifas Carmesim Descascadas", points: 1 },
      { id: "warped_stem", pt: "Caule Distorcido", points: 1 },
      { id: "stripped_warped_stem", pt: "Caule Distorcido Descascado", points: 1 },
      { id: "warped_hyphae", pt: "Hifas Distorcidas", points: 1 },
      { id: "stripped_warped_hyphae", pt: "Hifas Distorcidas Descascadas", points: 1 },
      { id: "pixelmon:berry_log", pt: "Tronco de Fruta (Pixelmon)", points: 1 },
      { id: "pixelmon:apricorn_log", pt: "Tronco de Apricorn (Pixelmon)", points: 1 },
      { id: "pixelmon:ultra_jungle_log", pt: "Tronco de Ultra Selva", points: 1 },
      { id: "pixelmon:ultra_gingko_log", pt: "Tronco de Ultra Ginkgo", points: 1 },
      { id: "pixelmon:ultra_elm_log", pt: "Tronco de Ultra Olmo", points: 1 },
      { id: "fire", pt: "Fogo", points: 3 },
      { id: "soul_fire", pt: "Fogo das Almas", points: 3 },
      { id: "lava", pt: "Lava", points: 2 },
      { id: "netherrack", pt: "Netherrack", points: 2 },
      { id: "stone", pt: "Pedra", points: 1 },
      { id: "torch", pt: "Tocha", points: 2 },
      { id: "soul_torch", pt: "Tocha das Almas", points: 2 }
    ]
  },
  flying: {
    name: "Voador",
    color: "#A890F0",
    icon: "🕊️",
    blocks: [
      { id: "glass", pt: "Vidro", points: 2 },
      { id: "white_stained_glass", pt: "Vidro Tingido de Branco", points: 2 },
      { id: "orange_stained_glass", pt: "Vidro Tingido de Laranja", points: 2 },
      { id: "magenta_stained_glass", pt: "Vidro Tingido de Magenta", points: 2 },
      { id: "light_blue_stained_glass", pt: "Vidro Tingido de Azul Claro", points: 2 },
      { id: "yellow_stained_glass", pt: "Vidro Tingido de Amarelo", points: 2 },
      { id: "lime_stained_glass", pt: "Vidro Tingido de Lima", points: 2 },
      { id: "pink_stained_glass", pt: "Vidro Tingido de Rosa", points: 2 },
      { id: "gray_stained_glass", pt: "Vidro Tingido de Cinza", points: 2 },
      { id: "light_gray_stained_glass", pt: "Vidro Tingido de Cinza Claro", points: 2 },
      { id: "cyan_stained_glass", pt: "Vidro Tingido de Ciano", points: 2 },
      { id: "purple_stained_glass", pt: "Vidro Tingido de Roxo", points: 2 },
      { id: "blue_stained_glass", pt: "Vidro Tingido de Azul", points: 2 },
      { id: "brown_stained_glass", pt: "Vidro Tingido de Marrom", points: 2 },
      { id: "green_stained_glass", pt: "Vidro Tingido de Verde", points: 2 },
      { id: "red_stained_glass", pt: "Vidro Tingido de Vermelho", points: 2 },
      { id: "black_stained_glass", pt: "Vidro Tingido de Preto", points: 2 },
      { id: "glass_pane", pt: "Painel de Vidro", points: 2 },
      { id: "white_stained_glass_pane", pt: "Painel de Vidro Tingido de Branco", points: 2 },
      { id: "orange_stained_glass_pane", pt: "Painel de Vidro Tingido de Laranja", points: 2 },
      { id: "magenta_stained_glass_pane", pt: "Painel de Vidro Tingido de Magenta", points: 2 },
      { id: "light_blue_stained_glass_pane", pt: "Painel de Vidro Tingido de Azul Claro", points: 2 },
      { id: "yellow_stained_glass_pane", pt: "Painel de Vidro Tingido de Amarelo", points: 2 },
      { id: "lime_stained_glass_pane", pt: "Painel de Vidro Tingido de Lima", points: 2 },
      { id: "pink_stained_glass_pane", pt: "Painel de Vidro Tingido de Rosa", points: 2 },
      { id: "gray_stained_glass_pane", pt: "Painel de Vidro Tingido de Cinza", points: 2 },
      { id: "light_gray_stained_glass_pane", pt: "Painel de Vidro Tingido de Cinza Claro", points: 2 },
      { id: "cyan_stained_glass_pane", pt: "Painel de Vidro Tingido de Ciano", points: 2 },
      { id: "purple_stained_glass_pane", pt: "Painel de Vidro Tingido de Roxo", points: 2 },
      { id: "blue_stained_glass_pane", pt: "Painel de Vidro Tingido de Azul", points: 2 },
      { id: "brown_stained_glass_pane", pt: "Painel de Vidro Tingido de Marrom", points: 2 },
      { id: "green_stained_glass_pane", pt: "Painel de Vidro Tingido de Verde", points: 2 },
      { id: "red_stained_glass_pane", pt: "Painel de Vidro Tingido de Vermelho", points: 2 },
      { id: "black_stained_glass_pane", pt: "Painel de Vidro Tingido de Preto", points: 2 },
      { id: "beacon", pt: "Sinalizador", points: 3 },
      { id: "dispenser", pt: "Ejetor", points: 3 },
      { id: "grass_block", pt: "Bloco de Grama", points: 1 },
      { id: "jukebox", pt: "Tocador de Discos (Jukebox)", points: 2 },
      { id: "note_block", pt: "Bloco de Nota Musical", points: 2 }
    ]
  },
  ghost: {
    name: "Fantasma",
    color: "#705898",
    icon: "👻",
    blocks: [
      { id: "red_bed", pt: "Cama Vermelha", points: 2 },
      { id: "black_bed", pt: "Cama Preta", points: 2 },
      { id: "blue_bed", pt: "Cama Azul", points: 2 },
      { id: "brown_bed", pt: "Cama Marrom", points: 2 },
      { id: "cyan_bed", pt: "Cama Ciana", points: 2 },
      { id: "gray_bed", pt: "Cama Cinza", points: 2 },
      { id: "green_bed", pt: "Cama Verde", points: 2 },
      { id: "light_blue_bed", pt: "Cama Azul Claro", points: 2 },
      { id: "light_gray_bed", pt: "Cama Cinza Claro", points: 2 },
      { id: "lime_bed", pt: "Cama Lima", points: 2 },
      { id: "magenta_bed", pt: "Cama Magenta", points: 2 },
      { id: "orange_bed", pt: "Cama Laranja", points: 2 },
      { id: "pink_bed", pt: "Cama Rosa", points: 2 },
      { id: "purple_bed", pt: "Cama Roxa", points: 2 },
      { id: "white_bed", pt: "Cama Branca", points: 2 },
      { id: "yellow_bed", pt: "Cama Amarela", points: 2 },
      { id: "emerald_block", pt: "Bloco de Esmeralda", points: 3 },
      { id: "bookshelf", pt: "Estante de Livros", points: 3 },
      { id: "white_carpet", pt: "Tapete Branco", points: 3 },
      { id: "orange_carpet", pt: "Tapete Laranja", points: 3 },
      { id: "magenta_carpet", pt: "Tapete Magenta", points: 3 },
      { id: "light_blue_carpet", pt: "Tapete Azul Claro", points: 3 },
      { id: "yellow_carpet", pt: "Tapete Amarelo", points: 3 },
      { id: "lime_carpet", pt: "Tapete Lima", points: 3 },
      { id: "pink_carpet", pt: "Tapete Rosa", points: 3 },
      { id: "gray_carpet", pt: "Tapete Cinza", points: 3 },
      { id: "light_gray_carpet", pt: "Tapete Cinza Claro", points: 3 },
      { id: "cyan_carpet", pt: "Tapete Ciano", points: 3 },
      { id: "purple_carpet", pt: "Tapete Roxo", points: 3 },
      { id: "blue_carpet", pt: "Tapete Azul", points: 3 },
      { id: "brown_carpet", pt: "Tapete Marrom", points: 3 },
      { id: "green_carpet", pt: "Tapete Verde", points: 3 },
      { id: "red_carpet", pt: "Tapete Vermelho", points: 3 },
      { id: "black_carpet", pt: "Tapete Preto", points: 3 },
      { id: "cobweb", pt: "Teia de Aranha", points: 2 },
      { id: "iron_bars", pt: "Grades de Ferro", points: 3 },
      { id: "jukebox", pt: "Tocador de Discos (Jukebox)", points: 3 },
      { id: "creeper_head", pt: "Cabeça de Creeper", points: 3 },
      { id: "zombie_head", pt: "Cabeça de Zumbi", points: 3 },
      { id: "skeleton_skull", pt: "Crânio de Esqueleto", points: 3 },
      { id: "wither_skeleton_skull", pt: "Crânio de Esqueleto Wither", points: 3 },
      { id: "mossy_cobblestone", pt: "Pedregulho Musgoso", points: 1 },
      { id: "mycelium", pt: "Micélio", points: 2 }
    ]
  },
  grass: {
    name: "Planta",
    color: "#78C850",
    icon: "🌿",
    blocks: [
      { id: "carrots", pt: "Cenouras", points: 3 },
      { id: "fern", pt: "Samambaia", points: 1 },
      { id: "grass", pt: "Grama", points: 1 },
      { id: "grass_block", pt: "Bloco de Grama", points: 1 },
      { id: "hay_block", pt: "Bloco de Feno", points: 3 },
      { id: "jack_o_lantern", pt: "Lanterna de Abóbora", points: 3 },
      { id: "melon", pt: "Melancia", points: 3 },
      { id: "melon_stem", pt: "Caule de Melancia", points: 2 },
      { id: "pixelmon:moss_rock", pt: "Pedra de Musgo", points: 2 },
      { id: "pumpkin", pt: "Abóbora", points: 3 },
      { id: "pumpkin_stem", pt: "Caule de Abóbora", points: 2 },
      { id: "wheat", pt: "Trigo", points: 3 },
      { id: "dead_bush", pt: "Arbusto Seco", points: 1 }
    ]
  },
  ground: {
    name: "Terra",
    color: "#E0C068",
    icon: "🪵",
    blocks: [
      { id: "bedrock", pt: "Rocha Matriz (Bedrock)", points: 4 },
      { id: "cactus", pt: "Cacto", points: 2 },
      { id: "clay", pt: "Argila", points: 2 },
      { id: "terracotta", pt: "Terracota", points: 2 },
      { id: "sand", pt: "Areia", points: 1 },
      { id: "sandstone", pt: "Arenito", points: 2 },
      { id: "soul_sand", pt: "Areia de Almas", points: 1 },
      { id: "white_terracotta", pt: "Terracota Branca", points: 3 },
      { id: "orange_terracotta", pt: "Terracota Laranja", points: 3 },
      { id: "magenta_terracotta", pt: "Terracota Magenta", points: 3 },
      { id: "light_blue_terracotta", pt: "Terracota Azul Claro", points: 3 },
      { id: "yellow_terracotta", pt: "Terracota Amarela", points: 3 },
      { id: "lime_terracotta", pt: "Terracota Lima", points: 3 },
      { id: "pink_terracotta", pt: "Terracota Rosa", points: 3 },
      { id: "gray_terracotta", pt: "Terracota Cinza", points: 3 },
      { id: "light_gray_terracotta", pt: "Terracota Cinza Claro", points: 3 },
      { id: "cyan_terracotta", pt: "Terracota Ciana", points: 3 },
      { id: "purple_terracotta", pt: "Terracota Roxa", points: 3 },
      { id: "blue_terracotta", pt: "Terracota Azul", points: 3 },
      { id: "brown_terracotta", pt: "Terracota Marrom", points: 3 },
      { id: "green_terracotta", pt: "Terracota Verde", points: 3 },
      { id: "red_terracotta", pt: "Terracota Vermelha", points: 3 },
      { id: "black_terracotta", pt: "Terracota Preta", points: 3 }
    ]
  },
  ice: {
    name: "Gelo",
    color: "#98D8D8",
    icon: "❄️",
    blocks: [
      { id: "ice", pt: "Gelo", points: 2 },
      { id: "pixelmon:ice_rock", pt: "Pedra de Gelo", points: 2 },
      { id: "packed_ice", pt: "Gelo Compacto", points: 3 },
      { id: "blue_ice", pt: "Gelo Azul", points: 3 },
      { id: "snow_block", pt: "Bloco de Neve", points: 2 },
      { id: "snow", pt: "Neve", points: 1 }
    ]
  },
  normal: {
    name: "Normal",
    color: "#A8A878",
    icon: "⚪",
    blocks: [
      { id: "cake", pt: "Bolo", points: 3 },
      { id: "dirt", pt: "Terra", points: 1 },
      { id: "oak_fence", pt: "Cerca de Carvalho", points: 2 },
      { id: "acacia_fence", pt: "Cerca de Acácia", points: 2 },
      { id: "dark_oak_fence", pt: "Cerca de Carvalho Escuro", points: 2 },
      { id: "spruce_fence", pt: "Cerca de Pinheiro", points: 2 },
      { id: "birch_fence", pt: "Cerca de Bétula", points: 2 },
      { id: "jungle_fence", pt: "Cerca de Selva", points: 2 },
      { id: "crimson_fence", pt: "Cerca Carmesim", points: 2 },
      { id: "warped_fence", pt: "Cerca Distorcida", points: 2 },
      { id: "pixelmon:blue_berry_wood_fence", pt: "Cerca de Madeira de Fruta Azul", points: 2 },
      { id: "pixelmon:green_berry_wood_fence", pt: "Cerca de Madeira de Fruta Verde", points: 2 },
      { id: "pixelmon:pink_berry_wood_fence", pt: "Cerca de Madeira de Fruta Rosa", points: 2 },
      { id: "pixelmon:purple_berry_wood_fence", pt: "Cerca de Madeira de Fruta Roxa", points: 2 },
      { id: "pixelmon:red_berry_wood_fence", pt: "Cerca de Madeira de Fruta Vermelha", points: 2 },
      { id: "pixelmon:yellow_berry_wood_fence", pt: "Cerca de Madeira de Fruta Amarela", points: 2 },
      { id: "pixelmon:ultra_jungle_fence", pt: "Cerca de Ultra Selva", points: 2 },
      { id: "pixelmon:ultra_gingko_fence", pt: "Cerca de Ultra Ginkgo", points: 2 },
      { id: "pixelmon:ultra_elm_fence", pt: "Cerca de Ultra Olmo", points: 2 },
      { id: "nether_brick_fence", pt: "Cerca de Tijolos do Nether", points: 2 },
      { id: "grass_block", pt: "Bloco de Grama", points: 1 },
      { id: "stone", pt: "Pedra", points: 1 },
      { id: "white_wool", pt: "Lã Branca", points: 1 },
      { id: "orange_wool", pt: "Lã Laranja", points: 1 },
      { id: "magenta_wool", pt: "Lã Magenta", points: 1 },
      { id: "light_blue_wool", pt: "Lã Azul Claro", points: 1 },
      { id: "yellow_wool", pt: "Lã Amarela", points: 1 },
      { id: "lime_wool", pt: "Lã Lima", points: 1 },
      { id: "pink_wool", pt: "Lã Rosa", points: 1 },
      { id: "gray_wool", pt: "Lã Cinza", points: 1 },
      { id: "light_gray_wool", pt: "Lã Cinza Claro", points: 1 },
      { id: "cyan_wool", pt: "Lã Ciana", points: 1 },
      { id: "purple_wool", pt: "Lã Roxa", points: 1 },
      { id: "blue_wool", pt: "Lã Azul", points: 1 },
      { id: "brown_wool", pt: "Lã Marrom", points: 1 },
      { id: "green_wool", pt: "Lã Verde", points: 1 },
      { id: "red_wool", pt: "Lã Vermelha", points: 1 },
      { id: "black_wool", pt: "Lã Preta", points: 1 }
    ]
  },
  poison: {
    name: "Venenoso",
    color: "#A040A0",
    icon: "☠️",
    blocks: [
      { id: "brewing_stand", pt: "Suporte de Poções", points: 3 },
      { id: "cobweb", pt: "Teia de Aranha", points: 2 },
      { id: "grass_block", pt: "Bloco de Grama", points: 1 },
      { id: "brown_mushroom", pt: "Cogumelo Marrom", points: 1 },
      { id: "red_mushroom", pt: "Cogumelo Vermelho", points: 2 },
      { id: "brown_mushroom_block", pt: "Bloco de Cogumelo Marrom", points: 2 },
      { id: "red_mushroom_block", pt: "Bloco de Cogumelo Vermelho", points: 3 },
      { id: "mycelium", pt: "Micélio", points: 2 },
      { id: "sponge", pt: "Esponja", points: 2 },
      { id: "wet_sponge", pt: "Esponja Molhada", points: 2 }
    ]
  },
  psychic: {
    name: "Psíquico",
    color: "#F85888",
    icon: "🔮",
    blocks: [
      { id: "diamond_block", pt: "Bloco de Diamante", points: 3 },
      { id: "emerald_block", pt: "Bloco de Esmeralda", points: 3 },
      { id: "quartz_block", pt: "Bloco de Quartzo", points: 3 },
      { id: "bookshelf", pt: "Estante de Livros", points: 2 },
      { id: "white_carpet", pt: "Tapete Branco", points: 1 },
      { id: "orange_carpet", pt: "Tapete Laranja", points: 1 },
      { id: "magenta_carpet", pt: "Tapete Magenta", points: 1 },
      { id: "light_blue_carpet", pt: "Tapete Azul Claro", points: 1 },
      { id: "yellow_carpet", pt: "Tapete Amarelo", points: 1 },
      { id: "lime_carpet", pt: "Tapete Lima", points: 1 },
      { id: "pink_carpet", pt: "Tapete Rosa", points: 1 },
      { id: "gray_carpet", pt: "Tapete Cinza", points: 1 },
      { id: "light_gray_carpet", pt: "Tapete Cinza Claro", points: 1 },
      { id: "cyan_carpet", pt: "Tapete Ciano", points: 1 },
      { id: "purple_carpet", pt: "Tapete Roxo", points: 1 },
      { id: "blue_carpet", pt: "Tapete Azul", points: 1 },
      { id: "brown_carpet", pt: "Tapete Marrom", points: 1 },
      { id: "green_carpet", pt: "Tapete Verde", points: 1 },
      { id: "red_carpet", pt: "Tapete Vermelho", points: 1 },
      { id: "black_carpet", pt: "Tapete Preta", points: 1 },
      { id: "enchanting_table", pt: "Mesa de Encantamentos", points: 3 },
      { id: "oak_sign", pt: "Placa de Carvalho", points: 2 },
      { id: "spruce_sign", pt: "Placa de Pinheiro", points: 2 },
      { id: "birch_sign", pt: "Placa de Bétula", points: 2 },
      { id: "acacia_sign", pt: "Placa de Acácia", points: 2 },
      { id: "jungle_sign", pt: "Placa de Selva", points: 2 },
      { id: "dark_oak_sign", pt: "Placa de Carvalho Escuro", points: 2 },
      { id: "crimson_sign", pt: "Placa Carmesim", points: 2 },
      { id: "warped_sign", pt: "Placa Distorcida", points: 2 },
      { id: "oak_wall_sign", pt: "Placa de Parede de Carvalho", points: 2 },
      { id: "spruce_wall_sign", pt: "Placa de Parede de Pinheiro", points: 2 },
      { id: "birch_wall_sign", pt: "Placa de Parede de Bétula", points: 2 },
      { id: "acacia_wall_sign", pt: "Placa de Parede de Acácia", points: 2 },
      { id: "jungle_wall_sign", pt: "Placa de Parede de Selva", points: 2 },
      { id: "dark_oak_wall_sign", pt: "Placa de Parede de Carvalho Escuro", points: 2 },
      { id: "crimson_wall_sign", pt: "Placa de Parede Carmesim", points: 2 },
      { id: "warped_wall_sign", pt: "Placa de Parede Distorcida", points: 2 }
    ]
  },
  rock: {
    name: "Pedra",
    color: "#B8A038",
    icon: "🪨",
    blocks: [
      { id: "bedrock", pt: "Rocha Matriz (Bedrock)", points: 3 },
      { id: "coal_block", pt: "Bloco de Carvão", points: 3 },
      { id: "cobblestone", pt: "Pedregulho", points: 1 },
      { id: "end_stone", pt: "Pedra do Fim", points: 3 },
      { id: "pixelmon:fossil", pt: "Fóssil (Pixelmon)", points: 2 },
      { id: "furnace", pt: "Fornalha", points: 2 },
      { id: "stone", pt: "Pedra", points: 1 },
      { id: "torch", pt: "Tocha", points: 2 },
      { id: "soul_torch", pt: "Tocha das Almas", points: 2 }
    ]
  },
  steel: {
    name: "Aço",
    color: "#B8B8D0",
    icon: "🛡️",
    blocks: [
      { id: "gold_block", pt: "Bloco de Ouro", points: 3 },
      { id: "iron_block", pt: "Bloco de Ferro", points: 3 },
      { id: "detector_rail", pt: "Trilho Detector", points: 2 },
      { id: "iron_bars", pt: "Grades de Ferro", points: 2 },
      { id: "iron_door", pt: "Porta de Ferro", points: 2 },
      { id: "piston", pt: "Pistão", points: 2 },
      { id: "sticky_piston", pt: "Pistão Grudento", points: 2 },
      { id: "piston_head", pt: "Cabeça de Pistão", points: 2 },
      { id: "rail", pt: "Trilho", points: 1 },
      { id: "stone", pt: "Pedra", points: 1 }
    ]
  },
  water: {
    name: "Água",
    color: "#6890F0",
    icon: "💧",
    blocks: [
      { id: "lily_pad", pt: "Vitória-régia", points: 3 },
      { id: "sea_lantern", pt: "Lanterna do Mar", points: 3 },
      { id: "sponge", pt: "Esponja", points: 2 },
      { id: "wet_sponge", pt: "Esponja Molhada", points: 2 },
      { id: "sugar_cane", pt: "Cana-de-açúcar", points: 2 },
      { id: "water", pt: "Água", points: 1 },
      { id: "pixelmon:water_stone_ore", pt: "Minério de Pedra da Água", points: 2 }
    ]
  }
};
